require("neo-tree").setup({
  sources = {
    "filesystem",
    "buffers",
    "git_status",
    -- "document_symbols",
  },
  use_default_mappings = false,
  source_selector = {
    winbar = true,
    statusline = false,
    sources = {
      { source = "filesystem", display_name = " 󰉓  " },
      { source = "buffers", display_name = " 󰈚 " },
      { source = "git_status", display_name = " 󰊢 " },
      { source = "document_symbols", display_name = " 󰌗 " },
    },
    tabs_layout = "active",
    truncation_character = "…",
    highlight_tab = "NeoTreeTabInactive",
    highlight_tab_active = "NeoTreeTabActive",
    highlight_background = "NeoTreeTabInactive",
    highlight_separator = "NeoTreeTabSeparatorInactive",
    highlight_separator_active = "NeoTreeTabSeparatorActive",
  },
  close_if_last_window = false,
  popup_border_style = "single",
  enable_git_status = true,
  enable_diagnostics = false,
  enable_normal_mode_for_inputs = false,
  open_files_do_not_replace_types = { "terminal", "trouble", "qf" },
  sort_case_insensitive = false,
  sort_function = nil,
  default_component_configs = {
    container = {
      enable_character_fade = true,
    },
    indent = {
      indent_size = 2,
      padding = 1,
      with_markers = true,
      indent_marker = "│",
      last_indent_marker = "└",
      highlight = "NeoTreeIndentMarker",
      with_expanders = true,
      expander_collapsed = "",
      expander_expanded = "",
      expander_highlight = "NeoTreeExpander",
    },
    icon = {
      folder_closed = "",
      folder_open = "",
      folder_empty = "󰜌",
      default = "*",
      highlight = "NeoTreeFileIcon",
    },
    modified = {
      symbol = "[+]",
      highlight = "NeoTreeModified",
    },
    name = {
      trailing_slash = false,
      use_git_status_colors = true,
      highlight = "NeoTreeFileName",
    },
    git_status = {
      symbols = {
        added = "",
        modified = "",
        deleted = "✖",
        renamed = "󰁕",
        untracked = "",
        ignored = "",
        unstaged = "󰄱",
        staged = "",
        conflict = "",
      },
    },
  },
  commands = {},
  window = {
    position = "left",
    width = 40,
    mapping_options = {
      noremap = true,
      nowait = true,
    },
    mappings = {
      ["o"] = "toggle_node",
      ["O"] = "expand_all_nodes",
      ["<cr>"] = "open",
      ["<esc>"] = "cancel",
      ["P"] = { "toggle_preview", config = { use_float = true } },
      ["s"] = "open_split",
      ["v"] = "open_vsplit",
      ["t"] = "open_tabnew",
      -- ["w"] = "open_with_window_picker",
      -- ['C'] = 'close_all_subnodes',
      ["z"] = "close_node",
      ["Z"] = "close_all_nodes",
      --["Z"] = "expand_all_nodes",
      ["a"] = {
        "add",
        config = {
          show_path = "none", -- "none" |  "relative" | "absolute"
        },
      },
      ["d"] = "delete",
      ["r"] = "rename",
      ["m"] = "move",
      ["q"] = "close_window",
      ["R"] = "refresh",
      ["?"] = "show_help",
      ["<"] = "prev_source",
      [">"] = "next_source",
    },
  },
  nesting_rules = {},
  filesystem = {
    group_empty_dirs = true,
    filtered_items = {
      visible = false,
      hide_dotfiles = false,
      hide_gitignored = false,
      hide_hidden = false,
      hide_by_name = {},
      hide_by_pattern = {},
      always_show = {},
      never_show = {
        ".DS_Store",
        "thumbs.db",
      },
      never_show_by_pattern = {},
    },
    follow_current_file = {
      enabled = true,
      leave_dirs_open = false,
    },
    hijack_netrw_behavior = "open_default",
    use_libuv_file_watcher = false,
    window = {
      mappings = {
        -- ["<bs>"] = "navigate_up",
        -- ["."] = "set_root",
        -- ["H"] = "toggle_hidden",
        ["/"] = "fuzzy_finder",
        -- ["D"] = "fuzzy_finder_directory",
        -- ["#"] = "fuzzy_sorter", -- fuzzy sorting using the fzy algorithm
        -- ["D"] = "fuzzy_sorter_directory",
        ["f"] = "filter_on_submit",
        ["<c-x>"] = "clear_filter",
        ["[g"] = "prev_git_modified",
        ["]g"] = "next_git_modified",
      },
      fuzzy_finder_mappings = {
        ["<C-n>"] = "move_cursor_down",
        ["<C-p>"] = "move_cursor_up",
      },
    },
    commands = {},
  },
  buffers = {
    follow_current_file = {
      enabled = true,
      leave_dirs_open = false,
    },
    group_empty_dirs = true,
    show_unloaded = true,
    window = {
      mappings = {
        -- ["bd"] = "buffer_delete",
        -- ["<bs>"] = "navigate_up",
        -- ["."] = "set_root",
      },
    },
  },
  git_status = {
    window = {
      mappings = {
        -- ["A"] = "git_add_all",
        -- ["gu"] = "git_unstage_file",
        -- ["ga"] = "git_add_file",
        -- ["gr"] = "git_revert_file",
        -- ["gc"] = "git_commit",
        -- ["gp"] = "git_push",
        -- ["gg"] = "git_commit_and_push",
      },
    },
  },
  document_symbols = {
    follow_cursor = false,
    client_filters = "first",
    renderers = {
      root = {
        { "indent" },
        { "icon", default = "C" },
        { "name", zindex = 10 },
      },
      symbol = {
        { "indent", with_expanders = true },
        { "kind_icon", default = "?" },
        {
          "container",
          content = {
            { "name", zindex = 10 },
            { "kind_name", zindex = 20, align = "right" },
          },
        },
      },
    },
    window = {
      mappings = {
        ["<cr>"] = "jump_to_symbol",
      },
    },
    custom_kinds = {},
    kinds = {
      Unknown = { icon = "?", hl = "" },
      Root = { icon = "", hl = "NeoTreeRootName" },
      File = { icon = "󰈙", hl = "Tag" },
      Module = { icon = "", hl = "Exception" },
      Namespace = { icon = "󰌗", hl = "Include" },
      Package = { icon = "󰏖", hl = "Label" },
      Class = { icon = "󰌗", hl = "Include" },
      Method = { icon = "", hl = "Function" },
      Property = { icon = "󰆧", hl = "@property" },
      Field = { icon = "", hl = "@field" },
      Constructor = { icon = "", hl = "@constructor" },
      Enum = { icon = "󰒻", hl = "@number" },
      Interface = { icon = "", hl = "Type" },
      Function = { icon = "󰊕", hl = "Function" },
      Variable = { icon = "", hl = "@variable" },
      Constant = { icon = "", hl = "Constant" },
      String = { icon = "󰀬", hl = "String" },
      Number = { icon = "󰎠", hl = "Number" },
      Boolean = { icon = "", hl = "Boolean" },
      Array = { icon = "󰅪", hl = "Type" },
      Object = { icon = "󰅩", hl = "Type" },
      Key = { icon = "󰌋", hl = "" },
      Null = { icon = "", hl = "Constant" },
      EnumMember = { icon = "", hl = "Number" },
      Struct = { icon = "󰌗", hl = "Type" },
      Event = { icon = "", hl = "Constant" },
      Operator = { icon = "󰆕", hl = "Operator" },
      TypeParameter = { icon = "󰊄", hl = "Type" },

      -- ccls
      -- TypeAlias = { icon = ' ', hl = 'Type' },
      -- Parameter = { icon = ' ', hl = '@parameter' },
      -- StaticMethod = { icon = '󰠄 ', hl = 'Function' },
      -- Macro = { icon = ' ', hl = 'Macro' },
    },
  },
})
