-- [nfnl] Compiled from nvim/fnl/neogit.fnl by https://github.com/Olical/nfnl, do not edit.
local neogit = require("neogit")
local git_services = {["github.com"] = "https://github.com/${owner}/${repository}/compare/${branch_name}?expand=1", ["bitbucket.org"] = "https://bitbucket.org/${owner}/${repository}/pull-requests/new?source=${branch_name}&t=1", ["gitlab.com"] = "https://gitlab.com/${owner}/${repository}/merge_requests/new?merge_request[source_branch]=${branch_name}"}
local signs = {hunk = {"", ""}, item = {"\239\132\133", "\239\132\135"}, section = {"\239\132\133", "\239\132\135"}}
local sections = {sequencer = {hidden = false, folded = false}, untracked = {hidden = false, folded = false}, unstaged = {hidden = false, folded = false}, staged = {hidden = false, folded = false}, stashes = {folded = true, hidden = false}, unpulled_upstream = {folded = true, hidden = false}, unmerged_upstream = {hidden = false, folded = false}, unpulled_pushRemote = {folded = true, hidden = false}, unmerged_pushRemote = {hidden = false, folded = false}, recent = {folded = true, hidden = false}, rebase = {folded = true, hidden = false}}
local ignored_settings = {"NeogitPushPopup--force-with-lease", "NeogitPushPopup--force", "NeogitPullPopup--rebase", "NeogitLogPopup--", "NeogitCommitPopup--allow-empty", "NeogitRevertPopup--no-edit"}
local integrations = {telescope = nil, diffview = true, fzf_lua = nil}
local finder = {["<cr>"] = "Select", ["<c-c>"] = "Close", ["<esc>"] = "Close", ["<c-n>"] = "Next", ["<c-p>"] = "Previous", ["<down>"] = "Next", ["<up>"] = "Previous", ["<tab>"] = "MultiselectToggleNext", ["<s-tab>"] = "MultiselectTogglePrevious", ["<c-j>"] = "NOP"}
local popup = {["?"] = "HelpPopup", A = "CherryPickPopup", D = "DiffPopup", M = "RemotePopup", P = "PushPopup", X = "ResetPopup", Z = "StashPopup", i = "IgnorePopup", t = "TagPopup", b = "BranchPopup", c = "CommitPopup", f = "FetchPopup", l = "LogPopup", m = "MergePopup", p = "PullPopup", r = "RebasePopup", v = "RevertPopup"}
local status = {q = "Close", I = "InitRepo", ["1"] = "Depth1", ["2"] = "Depth2", ["3"] = "Depth3", ["4"] = "Depth4", ["<tab>"] = "Toggle", x = "Discard", s = "Stage", S = "StageUnstaged", ["<c-s>"] = "StageAll", u = "Unstage", U = "UnstageStaged", d = "DiffAtFile", ["$"] = "CommandHistory", ["#"] = "Console", ["<c-r>"] = "RefreshBuffer", ["<enter>"] = "GoToFile", ["<c-v>"] = "VSplitOpen", ["<c-x>"] = "SplitOpen", ["<c-t>"] = "TabOpen", ["{"] = "GoToPreviousHunkHeader", ["}"] = "GoToNextHunkHeader"}
local mappings = {finder = finder, popup = popup, status = status}
local function _1_()
end
local function _2_()
  return (vim.fn.executable("gpg") == 1)
end
return neogit.setup({disable_commit_confirmation = true, filewatcher = {interval = 1000, enabled = false}, telescope_sorter = _1_, disable_insert_on_commit = true, use_per_project_settings = true, remember_settings = true, auto_refresh = true, sort_branches = "-committerdate", kind = "split", disable_line_numbers = true, console_timeout = 2000, auto_show_console = true, notification_icon = "\243\176\138\162", status = {recent_commit_count = 10}, commit_editor = {kind = "auto"}, commit_select_view = {kind = "tab"}, commit_view = {kind = "vsplit", verify_commit = _2_}, log_view = {kind = "tab"}, rebase_editor = {kind = "auto"}, reflog_view = {kind = "tab"}, merge_editor = {kind = "auto"}, description_editor = {kind = "auto"}, tag_editor = {kind = "auto"}, preview_buffer = {kind = "split"}, popup = {kind = "split"}, git_services = git_services, signs = signs, integrations = integrations, sections = sections, ignored_settings = ignored_settings, mappings = mappings, use_default_keymaps = false, disable_context_highlighting = false, disable_hint = false})
