-- [nfnl] Compiled from nvim/fnl/prelude.fnl by https://github.com/Olical/nfnl, do not edit.
local cache_path = vim.fn.stdpath("cache")
local o = vim.o
o["helplang"] = "ja"
o["mouse"] = "a"
o["ignorecase"] = true
o["smartcase"] = true
o["hlsearch"] = true
o["incsearch"] = true
o["hidden"] = true
o["termguicolors"] = true
o["showmode"] = false
o["autoread"] = true
o["showmatch"] = true
o["startofline"] = false
o["completeopt"] = "menu,menuone,noinsert"
o["number"] = true
o["signcolumn"] = "yes"
o["virtualedit"] = "block"
o["cmdheight"] = 0
o["laststatus"] = 3
o["undofile"] = true
o["undodir"] = (cache_path .. "/undo")
do end (o)["swapfile"] = true
o["directory"] = (cache_path .. "/swap")
do end (o)["winwidth"] = 20
o["winminwidth"] = 20
o["expandtab"] = true
o["tabstop"] = 2
o["shiftwidth"] = 2
o["foldlevel"] = 99
o["foldlevelstart"] = 99
o["backup"] = true
o["backupcopy"] = "yes"
o["backupdir"] = (cache_path .. "/backup")
do end (o)["diffopt"] = "internal,filler,closeoff,vertical"
return nil
